package com.gmdinnovacion.beneficiosgmd.disfruta.domain.model;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table "POINT".
 */
public class Point {

    private Long id;
    /** Not-null value. */
    private int idProveedor;
    private String latitud;
    private String longitud;
    private String hora;
    private String fecha;

    public Point(Long id, int idProveedor, String latitud, String longitud, String hora, String fecha) {
        this.id = id;
        this.idProveedor = idProveedor;
        this.latitud = latitud;
        this.longitud = longitud;
        this.hora = hora;
        this.fecha = fecha;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public int getIdProveedor() {
        return idProveedor;
    }

    public void setIdProveedor(int idProveedor) {
        this.idProveedor = idProveedor;
    }

    public String getLatitud() {
        return latitud;
    }

    public void setLatitud(String latitud) {
        this.latitud = latitud;
    }

    public String getLongitud() {
        return longitud;
    }

    public void setLongitud(String longitud) {
        this.longitud = longitud;
    }

    public String getHora() {
        return hora;
    }

    public void setHora(String hora) {
        this.hora = hora;
    }

    public String getFecha() {
        return fecha;
    }

    public void setFecha(String fecha) {
        this.fecha = fecha;
    }
}
